name: Lumino API Tests CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-api-tests:
    name: Run Lumino API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html
          
      
      - name: Start Lumino Backend Proxy Server (Mocked for CI)
        run: echo "Assuming Lumino server is started/mocked for CI"

      - name: Run Lumino API Collection via Newman
        run: |
          newman run postman/Lumino.postman_collection.json \
            -e postman/Lumino.postman_environment.json \
            -r cli,html \
            --reporter-html-export "newman_report.html"

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: newman_report.html
